openapi: 3.0.3
info:
  title: h23s_08_app
  description: ""
  version: 0.0.0
servers:
  - url: https://dev-tqk-h23s-08-app.trap.show/api/
    description: 仮
paths:
  /users:
    get:
      summary: ユーザー一覧
      operationId: getUsers
      responses:
        "200":
          description: Ok
          content:
            json/application:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "00000000-0000-0000-0000-000000000000"
                    name:
                      type: string
                      example: "tqk"
  /groups:
    get:
      summary: グループ一覧
      operationId: getGroups
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "00000000-0000-0000-0000-000000000000"
                    name:
                      type: string
                      example: "traO"
    post:
      summary: グループ作成
      operationId: postGroups
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "traO"
      parameters: []
      responses:
        "201":
          description: |
            Created
            作成しました
    put:
      summary: グループ編集
      operationId: putGroups
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "00000000-0000-0000-0000-000000000000"
                name:
                  type: string
                  example: "traO"
      parameters: []
      responses:
        "200":
          description: |
            Created
            編集しました
  /groups/details?id={group_id}:
    get:
      summary: グループ詳細
      operationId: getGroupsDetails
      parameters:
        - name: group_id
          in: query
          description: グループID
          required: true
          schema:
            type: string
            example: "00000000-0000-0000-0000-000000000000"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "00000000-0000-0000-0000-000000000000"
                  name:
                    type: string
                    example: "traO"
                  created_at:
                    type: string
                    example: "2023-06-16T23:04:55.000Z"
                  members:
                    type: array
                    items:
                      type: string
                      example: "00000000-0000-0000-0000-000000000000"
  /groups/join:
    post:
      summary: グループに参加する
      operationId: postGroupsJoin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                group_id:
                  type: string
                  example: "00000000-0000-0000-0000-000000000000"
                user_id:
                  type: string
                  example: "00000000-0000-0000-0000-000000000000"
      parameters: []
      responses:
        "200":
          description: |
            Created
            参加しました
  /groups/leave:
    post:
      summary: グループから離脱する
      operationId: postGroupsLeave
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                group_id:
                  type: string
                  example: "00000000-0000-0000-0000-000000000000"
                user_id:
                  type: string
                  example: "00000000-0000-0000-0000-000000000000"
      parameters: []
      responses:
        "200":
          description: |
            Created
            離脱しました
