openapi: 3.0.3
info:
  title: tokuteibu
  description: "勝手に特定部 座席にアイコン描けるやつ みんなで編集できるやつ"
  version: 0.0.0
servers:
  - url: https://tqk.trap.show/tokuteibu
    description: 予定
paths:
  /ping:
    get:
      summary: pong
      operationId: ping
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "pong"
  /events:
    get:
      summary: イベント一覧を取得する
      operationId: getEvents
      parameters:
        - name: page
          in: query
          description: ページ番号
          required: false
          schema:
            type: integer
        - name: match
          in: query
          description: 検索
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 0
                    title:
                      type: string
                      example: "traOmtg 2022 1"
    post:
      summary: イベントを追加する
      operationId: postEvents
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "traOmtg 2022 1"
      parameters: []
      responses:
        "200":
          description: |
            Ok
            追加しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 0
  /events/{id}:
    get:
      summary: イベントの情報を取得する
      operationId: getEventsId
      parameters:
        - name: id
          in: path
          description: イベント id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 0
                  title:
                    type: string
                    example: "traOmtg 2022 1"
                  description:
                    type: string
                    example: "traOmtg 2022 1"
                  seats:
                    type: array
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          y:
                            type: integer
                            example: 0
                          x:
                            type: integer
                            example: 0
                          content:
                            type: string
                            example: "@tqk"
                          editing:
                            type: boolean
                            example: false
                          editor:
                            type: string
                            example: "@tqk"

  /ws:
    get:
      summary: websocket で接続する
      description: |
        # websocket プロトコル

        ## サーバーに送信

        TextMessage で type と body をもつ json を送信します。

        例: `{"type":"START_EDITING","body":{"y":1,"x":3}}`

        ### 一覧と body の中身

        - `SET_VIEWING`: 見ているイベントを設定します
          - `id`: イベント id
        - `SET_TITLE`: イベントのタイトルを設定します(作成者のみ)
          - `title`: タイトル
        - `START_EDITING`: セルの編集を始めます
          - `y`: y 座標 0 ≤ y < H
          - `x`: x 座標 0 ≤ x < W
        - `FINISH_EDITING`: セルの編集を終わります
          - `content`: 編集後の内容
        - `CANCEL_EDITING`: セルの編集をキャンセルします
        - `INSERT_ROW`: 行を追加します
          - `y`: y 座標 0 ≤ y ≤ H
        - `INSERT_COLUMN`: 列を追加します
          - `x`: x 座標 0 ≤ x ≤ W

        ## サーバーから受信

        TextMessage で type と body をもつ json が送られます。

        例: `{"type":"START_EDITING","body":{"username":"@tqk","y":1,"x":3}}`

        ### 一覧と body の中身

        - `SET_TITLE`: タイトルが変更されました
          - `title`: タイトル
        - `START_EDITING`: セルが編集され始めました
          - `username`: 編集し始めたユーザー
          - `y`: y 座標 0 ≤ y < H
          - `x`: x 座標 0 ≤ x < W
        - `FINISH_EDITING`: セルが編集され終わりました
          - `y`: y 座標 0 ≤ y < H
          - `x`: x 座標 0 ≤ x < W
          - `content`: 内容
          - `by`: 編集したユーザー
        - `CANCEL_EDITING`: セルの編集がキャンセルされました
          - `y`: y 座標 0 ≤ y < H
          - `x`: x 座標 0 ≤ x < W
        - `INSERT_ROW`: 行が追加されました
          - `y`: y 座標 0 ≤ y ≤ H
        - `INSERT_COLUMN`: 列が追加されました
          - `x`: x 座標 0 ≤ x ≤ W

      responses:
        "101":
          description: |
            Switching Protocols
